name: CI
on: push

permissions:
  contents: write

jobs:
  lintfix:
    name: Lint and fix
    runs-on: ubuntu-latest
    steps:
      - name: ğŸš€ Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: ğŸ¯ Read .nvmrc
        run: echo "##[set-output name=NVMRC;]$(cat .nvmrc)"
        id: nvm

      - name: ğŸ—ï¸ Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '${{ steps.nvm.outputs.NVMRC }}'

      - name: ğŸ“¦ Setup pnpm - Install pnpm
        uses: pnpm/action-setup@v2
        with:
          run_install: false

      - name: ğŸ“¦ Setup pnpm -  Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: ğŸ“¦ Setup pnpm - Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: ğŸ“¦ Install dependencies
        run: pnpm install

      - name: ğŸ”¦ Run lint
        run: pnpm lint --fix

      - name: ğŸ–Œï¸ Run format
        run: pnpm format


      - name: ğŸ¾ Commit changes
        run: |
          git config --local user.email "56104765+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -a -m "chore: Auto-fix lint errors"

      - name: ğŸ¾ Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
