name: Tests

on: deployment_status

jobs:
  tests:
    name: Tests E2E
    timeout-minutes: 60
    runs-on: ubuntu-latest
    if: github.event_name == 'deployment_status' && github.event.deployment_status.state == 'success'
    steps:
      - name: ğŸš€ Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: ğŸ¯ Read .nvmrc
        run: echo "##[set-output name=NVMRC;]$(cat .nvmrc)"
        id: nvm

      - name: ğŸ—ï¸ Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '${{ steps.nvm.outputs.NVMRC }}'

      - name: ğŸ“¦ Setup pnpm - Install pnpm
        uses: pnpm/action-setup@v2
        with:
          run_install: false

      - name: ğŸ“¦ Setup pnpm -  Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: ğŸ“¦ Setup pnpm - Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: ğŸ“¦ Install dependencies
        run: pnpm install

      - name: ğŸŒ Install Playwright Browsers
        run: pnpm exec playwright install --with-deps

      - name: ğŸ­ Run Playwright tests
        run: pnpm test:e2e
        env:
          BASE_URL: ${{ github.event.deployment_status.target_url }}

      - name: ğŸ“Š Upload Playwright Report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

  e2e-tests-report:
    name: E2E Tests Report
    runs-on: ubuntu-latest
    needs: tests
    if: always()
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - name: ğŸ“¥ Get artifact
        uses: actions/download-artifact@v2
        with:
          name: playwright-report
          path: playwright-report

      - name: ğŸ“„ Setup Pages
        uses: actions/configure-pages@v2

      - name: ğŸ“¤ Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: playwright-report/

      - name: ğŸš€ Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
